#! /bin/sh

base=/Users/vern/warehouse/zeek-cpp
test=$base/testing/btest
so=$base/src/script_opt
build=$base/build
gen=CPP-gen-addl.h

export -n ZEEK_USE_CPP
export ZEEK_HASH_DIR=$test ZEEK_ADD_CPP=
cd $test
cp $build/CPP-hashes.dat .
echo >$gen
# ../../auxil/btest/btest core >jlang-build.out 2>&1
../../auxil/btest/btest `cat jcore-b` >jlang-build.out 2>&1
grep -c '^namespace' $gen
mv $gen $so
cd $build
ninja >& errs || echo test suite build failed
